name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGmD94dDwXzq2FkV5g.n5Vqje9xby4"
            index: 0
          - recaptcha_token: "thr1.AAAAAGmD95M6tpY5VuVVbw.d4DtdxYnvic"
            index: 1
          - recaptcha_token: "thr1.AAAAAGmD9510vsAdm5vNAQ.h_g0hCYpij8"
            index: 2
          - recaptcha_token: "thr1.AAAAAGmD96jwPsgGnVjQMw.JAN-FzO0iDY"
            index: 3
          - recaptcha_token: "thr1.AAAAAGmD97W3vlUtvUhulg.OvVmlr1gv0c"
            index: 4
          - recaptcha_token: "thr1.AAAAAGmD98KxgWNIYBtrLA.V2XR_hm5iEI"
            index: 5
          - recaptcha_token: "thr1.AAAAAGmD99jmkmca1m3Ymg.ZTYcGAgaSTQ"
            index: 6
          - recaptcha_token: "thr1.AAAAAGmD9-X3U4MyTnaVbA.65skhv75Gsw"
            index: 7
          - recaptcha_token: "thr1.AAAAAGmD9_VKrQ3wAM03sQ.TzY8RETvXlU"
            index: 8
          - recaptcha_token: "thr1.AAAAAGmD-AcRmEuQ2zuCpw.Z9XQDkAT2PM"
            index: 9
          - recaptcha_token: "thr1.AAAAAGmD-CesZX27b2ZP4Q.dePF34kPT64"
            index: 10
          - recaptcha_token: "thr1.AAAAAGmD-EsCqMnAWX4U0A.DSHPonVF0wM"
            index: 11
          - recaptcha_token: "thr1.AAAAAGmD-FW8rrp87pDswQ.rZs-lStV7go"
            index: 12
          - recaptcha_token: "thr1.AAAAAGmD-GSPF_Xl4f00hQ.uG2pc3uAgaU"
            index: 13
          - recaptcha_token: "thr1.AAAAAGmD-He0AALLBobT6g.qhsGz2o62uk"
            index: 14
    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
