name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGl-wsTG0bzxFDOR3g.sy26vlIOThI"
            index: 0
          - recaptcha_token: "thr1.AAAAAGl-ws7BL5y-ZeNCeA.JM80T2zpwaM"
            index: 1
          - recaptcha_token: "thr1.AAAAAGl-wtiyy-oZkdBa3g.PwA6D6OlvTU"
            index: 2
          - recaptcha_token: "thr1.AAAAAGl-wuyKNhVa7C7sgg.EJmBQ8S3HQU"
            index: 3
          - recaptcha_token: "thr1.AAAAAGl-wwYwzc_st_WsMw.lUKjWtvlI9Y"
            index: 4
          - recaptcha_token: "thr1.AAAAAGl-wxUwRVtSBxCNeg.3abLc7yGfs8"
            index: 5
          - recaptcha_token: "thr1.AAAAAGl-wypom8zzTZFW1w.E4blArtG_Po"
            index: 6
          - recaptcha_token: "thr1.AAAAAGl-w0ND8DcPaa5GsA.UPnsQNaICCY"
            index: 7
          - recaptcha_token: "thr1.AAAAAGl-w3LzMLdV4lmk9A.J_YIxBw3UzI"
            index: 8
          - recaptcha_token: "thr1.AAAAAGl-w5Ko46qTGtAlgA.grSKv2kXRBs"
            index: 9
          - recaptcha_token: "thr1.AAAAAGl-w55xH2lXBiB2fg.OMX_gAsWPl0"
            index: 10
          - recaptcha_token: "thr1.AAAAAGl-w6vU5Qvja0d55A.TknquBIkr8o"
            index: 11
          - recaptcha_token: "thr1.AAAAAGl-w7021FGDc_etSQ.G5khokvjb3g"
            index: 12
          - recaptcha_token: "thr1.AAAAAGl-w-_RIMUWaDfWWw.UnNRo9k4Ji4"
            index: 13
          - recaptcha_token: "thr1.AAAAAGl-xAUayvLX2JSvMw.5hmlOFw96N4"
            index: 14
          - recaptcha_token: "thr1.AAAAAGl-xBoTK_6vURHAcA.nQgWNAdJkik"

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
