name: Host - Recaptcha Rooms - Group 3

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts-group3
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGmQxok336ocj6PQAA.OcKw0XzQwkw"
            index: 0
          - recaptcha_token: "thr1.AAAAAGmQxpmjjYgd1NfYlA.kY52OQQomWc"
            index: 1
          - recaptcha_token: "thr1.AAAAAGmQxrFBoJ5VREVFwQ.NosJcqjDK30"
            index: 2
          - recaptcha_token: "thr1.AAAAAGmQxsfwKqL-cu_qow.bAIXCLMxxvM"
            index: 3
          - recaptcha_token: "thr1.AAAAAGmQxtlpLZCjfbhdUg.XQfuMG7hXI4"
            index: 4
          - recaptcha_token: "thr1.AAAAAGmQxuRmMVkeL6s-Jg.179O_CnBeBQ"
            index: 5
          - recaptcha_token: "thr1.AAAAAGmQxvp_t5CFmEwT7A.CVnncan9T08"
            index: 6
          - recaptcha_token: "thr1.AAAAAGmQxwuHSIAhRhNunw.mIEiF6tjdK4"
            index: 7
          - recaptcha_token: "thr1.AAAAAGmQxxw6BuMC9KE2Kg.8O9eEjZ-P4k"
            index: 8
          - recaptcha_token: "thr1.AAAAAGmQxy6e7UoL2jm4CQ.XY7V_TRoMfg"
            index: 9
          - recaptcha_token: "thr1.AAAAAGmQxz0dOTnq8SHS2g.v6rGJAcXaJs"
            index: 10
          - recaptcha_token: "thr1.AAAAAGmQx09zGjBFSgf3RQ.qvPBfg89khI"
            index: 11
          - recaptcha_token: "thr1.AAAAAGmQx1xz3v1G6GABCA.vkjQwCH37Ek"
            index: 12
          - recaptcha_token: "thr1.AAAAAGmQx26DUP85aiH8mQ.aXjVIOPjQzQ"
            index: 13

    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
