name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGl-xi2qh61yHg-1TQ.unHu_pcZwkE"
            index: 0
          - recaptcha_token: "thr1.AAAAAGl-xj96oYvAMOP8aw.2l06wiBXjn8"
            index: 1
          - recaptcha_token: "thr1.AAAAAGl-xlCeszH3t0P5sA.Lg8m_3H8P88"
            index: 2
          - recaptcha_token: "thr1.AAAAAGl-xm6kJpQ9EwJG0A.y3MiqUNQ3O8"
            index: 3
          - recaptcha_token: "thr1.AAAAAGl-xqXQibsI5QVPJA.V_MBeuR3kOY"
            index: 4
          - recaptcha_token: "thr1.AAAAAGl-xuR8ED0QyWrWaQ.EGoU4SHf9Ko"
            index: 5
          - recaptcha_token: "thr1.AAAAAGl-x2nCS14vW97uWg.Yb_1thaqFXE"
            index: 6
          - recaptcha_token: "thr1.AAAAAGl-x5ZkRGu_V3N3Hg.kOXVmxOfQig"
            index: 7
          - recaptcha_token: "thr1.AAAAAGl-x7CNsarC9CzBVg._Uqssx5VmxY"
            index: 8
          - recaptcha_token: "thr1.AAAAAGl-x9PTMDIHebPtmQ.wqlA12fI9_g"
            index: 9
          - recaptcha_token: "thr1.AAAAAGl-x-YL666skiOd0Q.fu1s72jm910"
            index: 10
          - recaptcha_token: "thr1.AAAAAGl-x_99yXJ6B3cDAQ.lkRL5hsSn78"
            index: 11
          - recaptcha_token: "thr1.AAAAAGl-yB-Br6f19pVAjw.B_Yzc131jn0"
            index: 12
          - recaptcha_token: "thr1.AAAAAGl-yEJN3NxoWXm6ag.-AXKRS6-KcQ"
            index: 13
          - recaptcha_token: "thr1.AAAAAGl-yFQ6_YThaobX9g.W8iwJX8kc0k"
            index: 14
    steps:
      - name: üß© Checkout repo
        uses: actions/checkout@v4

      - name: üßπ Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ‚öôÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Instalar dependencias
        run: npm install

      - name: üöÄ Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "üëΩ"
