name: Run Kick Bot

on:
  workflow_dispatch:
    inputs:
      channel_id:
        description: 'Kick Channel ID'
        required: true
      threads:
        description: 'Number of viewers/threads'
        required: true
        default: 20

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tls-client websockets fake-useragent

      - name: Run Kick Bot
        env:
          CHANNEL_ID: ${{ github.event.inputs.channel_id }}
        run: |
          echo "Running bot for channel ID $CHANNEL_ID with $THREADS threads"
          python bot.py

